/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package trafficinfo.baseline.lambda.minimal

import kotlin.test.Test
import kotlin.test.assertNotEquals
import kotlin.test.assertEquals
import kotlinx.datetime.*

class AppTest {
  @Test
  fun testAppHasTime() {
    val classUnderTest = App()
    val input = HandlerInput()
    input.key = "time"
    var output = classUnderTest.handleRequest(input, null)
    assertEquals("time", output.key)
    assertNotEquals("", output.response)
  }

  @Test
  fun testAppHasNoTime() {
    val classUnderTest = App()
    val input = HandlerInput()
    input.key = ""
    var output = classUnderTest.handleRequest(input, null)
    assertEquals("", output.key)
    assertEquals("key 'time' must be set", output.response)
  }
}
